import type { Post } from "./types";

/**
 * Fixed reference timestamp sample post ages are generated from. Using a
 * constant instead of `Date.now()` keeps sample data identical between the
 * server render and the client render, avoiding hydration mismatches.
 */
export const SAMPLE_DATA_REFERENCE_TIME = new Date("2026-06-14T12:00:00.000Z").getTime();

/** Returns an ISO timestamp `hours` hours before the fixed reference time. */
function hoursAgo(hours: number): string {
  return new Date(SAMPLE_DATA_REFERENCE_TIME - hours * 60 * 60 * 1000).toISOString();
}

/**
 * Fictional, illustrative sample posts covering AI infrastructure, GPU compute,
 * decentralized compute / DePIN, AI inference and agents, cloud GPU pricing,
 * NVIDIA, hyperscalers, and major DePIN projects. None of these are real posts.
 */
export const samplePosts: Post[] = [
  {
    id: "post-001",
    authorName: "Maya Chen",
    handle: "@maya_builds_ai",
    text: "Spent the entire morning trying to get H100 access on AWS for a new training run and gave up. Anyone else stuck on GPU waitlists right now? Feels like the bottleneck of the year.",
    url: "https://x.com/maya_builds_ai/status/1893012345678900001",
    createdAt: hoursAgo(1),
    likes: 142,
    replies: 38,
    reposts: 21,
    views: 18900,
    followers: 8400,
  },
  {
    id: "post-002",
    authorName: "Daniel Okafor",
    handle: "@dokafor_ml",
    text: "NVIDIA H100s are basically impossible to get unless you're a hyperscaler with a direct allocation. Small AI labs are completely priced out of frontier compute right now. How is anyone supposed to compete without that access?",
    url: "https://x.com/dokafor_ml/status/1893012345678900002",
    createdAt: hoursAgo(1.5),
    likes: 980,
    replies: 156,
    reposts: 210,
    views: 142000,
    followers: 52000,
  },
  {
    id: "post-003",
    authorName: "Priya Raman",
    handle: "@priya_depin",
    text: "Akash Network just crossed a new milestone in GPU lease utilization this quarter. Decentralized compute is quietly turning into real infrastructure, not just a narrative.",
    url: "https://x.com/priya_depin/status/1893012345678900003",
    createdAt: hoursAgo(6),
    likes: 310,
    replies: 24,
    reposts: 64,
    views: 41000,
    followers: 19500,
  },
  {
    id: "post-004",
    authorName: "Tomas Vidal",
    handle: "@tomasv_ai",
    text: "Running inference for our production LLM now costs more per month than the entire training run did. Inference economics are the real bottleneck in AI right now, not training.",
    url: "https://x.com/tomasv_ai/status/1893012345678900004",
    createdAt: hoursAgo(3),
    likes: 540,
    replies: 92,
    reposts: 130,
    views: 76000,
    followers: 31000,
  },
  {
    id: "post-005",
    authorName: "Lena Brooks",
    handle: "@lena_agents",
    text: "Everyone is launching AI agents this year, but nobody talks about the compute cost of running thousands of autonomous agents 24/7. That cloud bill adds up fast.",
    url: "https://x.com/lena_agents/status/1893012345678900005",
    createdAt: hoursAgo(10),
    likes: 215,
    replies: 47,
    reposts: 38,
    views: 29800,
    followers: 14200,
  },
  {
    id: "post-006",
    authorName: "Sam Whitfield",
    handle: "@samw_cloud",
    text: "Cloud GPU pricing is wild right now. An A100 instance on Azure costs more per hour than some people's rent. There has to be a better way to access compute.",
    url: "https://x.com/samw_cloud/status/1893012345678900006",
    createdAt: hoursAgo(2),
    likes: 88,
    replies: 19,
    reposts: 12,
    views: 9400,
    followers: 6100,
  },
  {
    id: "post-007",
    authorName: "Grace Liu",
    handle: "@graceliu_tech",
    text: "AWS, Azure, and Google Cloud control most of the world's AI compute supply. That level of centralization is a long-term risk for the whole AI ecosystem, not just a pricing issue.",
    url: "https://x.com/graceliu_tech/status/1893012345678900007",
    createdAt: hoursAgo(14),
    likes: 670,
    replies: 88,
    reposts: 145,
    views: 98000,
    followers: 41000,
  },
  {
    id: "post-008",
    authorName: "Owen Park",
    handle: "@owenp_render",
    text: "Render Network's GPU marketplace just hit a new all-time high in completed rendering jobs this month. Distributed GPU compute for creative workloads keeps growing steadily.",
    url: "https://x.com/owenp_render/status/1893012345678900008",
    createdAt: hoursAgo(20),
    likes: 130,
    replies: 14,
    reposts: 22,
    views: 15600,
    followers: 9800,
  },
  {
    id: "post-009",
    authorName: "Hana Suzuki",
    handle: "@hana_subnet",
    text: "Bittensor's subnet ecosystem is expanding fast, but I still don't fully understand how the incentive mechanism translates into real usable compute value. Anyone have a good breakdown?",
    url: "https://x.com/hana_subnet/status/1893012345678900009",
    createdAt: hoursAgo(7),
    likes: 64,
    replies: 31,
    reposts: 9,
    views: 8700,
    followers: 5200,
  },
  {
    id: "post-010",
    authorName: "Marcus Webb",
    handle: "@marcusw_infra",
    text: "Aethir is positioning itself as a decentralized cloud for gaming and AI, with edge GPU nodes distributed globally. Curious how this actually scales compared to traditional cloud GPU providers.",
    url: "https://x.com/marcusw_infra/status/1893012345678900010",
    createdAt: hoursAgo(5),
    likes: 102,
    replies: 27,
    reposts: 18,
    views: 13400,
    followers: 7600,
  },
  {
    id: "post-011",
    authorName: "Ines Moreau",
    handle: "@ines_ml_research",
    text: "Gensyn wants to make distributed ML training trustless and verifiable across untrusted compute. If that works at scale, it massively expands usable supply for AI training.",
    url: "https://x.com/ines_ml_research/status/1893012345678900011",
    createdAt: hoursAgo(30),
    likes: 410,
    replies: 53,
    reposts: 71,
    views: 58000,
    followers: 26000,
  },
  {
    id: "post-012",
    authorName: "Carlos Diaz",
    handle: "@carlosd_sol",
    text: "Solana's DePIN sector keeps growing across GPU networks, wireless, and storage. Decentralized infrastructure finally feels like it's finding real product-market fit, not just incentives.",
    url: "https://x.com/carlosd_sol/status/1893012345678900012",
    createdAt: hoursAgo(48),
    likes: 295,
    replies: 36,
    reposts: 58,
    views: 39000,
    followers: 17800,
  },
  {
    id: "post-013",
    authorName: "Ava Thompson",
    handle: "@ava_dailylife",
    text: "Just tried the new AI chatbot app on my phone and it can summarize my emails now. Pretty cool honestly, saves me a bit of time every morning.",
    url: "https://x.com/ava_dailylife/status/1893012345678900013",
    createdAt: hoursAgo(16),
    likes: 22,
    replies: 3,
    reposts: 1,
    views: 1200,
    followers: 900,
  },
  {
    id: "post-014",
    authorName: "CryptoGains_Official",
    handle: "@cryptogains_x",
    text: "Huge airdrop incoming for our new DePIN GPU token! Early holders could see 100x potential. Don't miss out, DM me now for whitelist spots before it's gone!",
    url: "https://x.com/cryptogains_x/status/1893012345678900014",
    createdAt: hoursAgo(1.5),
    likes: 540,
    replies: 410,
    reposts: 890,
    views: 210000,
    followers: 3200,
  },
  {
    id: "post-015",
    authorName: "Felix Adler",
    handle: "@felixa_geo",
    text: "The next decade of AI compute access will be shaped as much by politics as engineering — export controls, chip war tensions, and subsidies for domestic GPU production will decide who has access.",
    url: "https://x.com/felixa_geo/status/1893012345678900015",
    createdAt: hoursAgo(60),
    likes: 180,
    replies: 64,
    reposts: 40,
    views: 27000,
    followers: 12000,
  },
];
